garabagh_core/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls.i18n import i18n_patterns
from django.utils.translation import gettext_lazy as _

urlpatterns = [
    path('admin/', admin.site.urls),
]

urlpatterns += i18n_patterns(
    path('', include('restaurant.urls', namespace='restaurant')),
)

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

restaurant/urls.py
from django.urls import path
from . import views

app_name = 'restaurant'

urlpatterns = [
    path('', views.home, name="home"),
    path('gallery/', views.gallery, name="gallery"),
    path('contact/', views.contact, name="contact"),
    path('menu/<int:category_id>', views.menu, name="menu"),
    path('map/', views.address_map, name="address"),
]

restaurant/models.py
from email.policy import default
from django.db import models
from django.utils import timezone

class Category(models.Model):
    name = models.CharField(max_length=50, null=False, blank=False)
    
    def __str__(self):
        return self.name
    
    class Meta:
        verbose_name_plural = "Categories"
    
    
class Menu(models.Model):
    menu_name = models.CharField(max_length=50)
    category = models.ForeignKey(Category, related_name="menu", on_delete=models.CASCADE, null=True, blank=True)
    picture = models.ImageField(default='images/default.png',upload_to='images')
    
    date_added = models.DateTimeField(default=timezone.now)
    
    def __str__(self):
        return self.menu_name
    
class MenuMeal(models.Model):
    meal_name = models.CharField(max_length=50)
    price = models.FloatField(blank=False)
    menu = models.ForeignKey(Menu, related_name="menu_meals", on_delete=models.CASCADE, null=True, blank=True)
    
    def __str__(self):
        return f'{self.menu} - {self.meal_name}'

class Gallery(models.Model):
    image = models.ImageField(default='images/default.png', upload_to='images', null=True)
    
    class Meta:
        verbose_name_plural = "Galleries"
        
    def __str__(self):
        return f'Image {self.id}'

restaurant/views.py
from multiprocessing import context
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse
from django.utils.translation import gettext as _
from django.utils.translation import get_language, activate, gettext
from .models import Category, Gallery, Menu
# Create your views here.

def home(request):
    context = {
        "last_added_menus":Menu.objects.order_by('-date_added')[:4],
    }
    return render(request,'restaurant/index.html', context)

def translate(language):
    cur_language = get_language()
    try: 
        activate(language)
    except:
        activate(cur_language)

def address_map(request):
    return render(request,'restaurant/address.html')
    
def contact(request):
    return render(request,'restaurant/contact.html')

def gallery(request):
    context = {
        'gallery_images':Gallery.objects.all(),
    }
    return render(request,'restaurant/gallery.html', context)

def menu(request, category_id):
    ctg = get_object_or_404(Category, pk = category_id)
    ctg_menu = ctg.menu.all()
    
    context = {
        'categories':Category.objects.all(),
        'menus':ctg_menu,
    }
    return render(request,'restaurant/menu.html', context)

restaurant/templates/restaurant/address.html
<!DOCTYPE html>
<head>    
    <meta http-equiv="content-type" content="text/html; charset=UTF-8" />
    
        <script>
            L_NO_TOUCH = false;
            L_DISABLE_3D = false;
        </script>
    
    <style>html, body {width: 100%;height: 100%;margin: 0;padding: 0;}</style>
    <style>#map {position:absolute;top:0;bottom:0;right:0;left:0;}</style>
    <script src="https://cdn.jsdelivr.net/npm/leaflet@1.6.0/dist/leaflet.js"></script>
    <script src="https://code.jquery.com/jquery-1.12.4.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.2.0/js/bootstrap.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/Leaflet.awesome-markers/2.0.2/leaflet.awesome-markers.js"></script>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/leaflet@1.6.0/dist/leaflet.css"/>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css"/>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap-theme.min.css"/>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.6.3/css/font-awesome.min.css"/>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/Leaflet.awesome-markers/2.0.2/leaflet.awesome-markers.css"/>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/gh/python-visualization/folium/folium/templates/leaflet.awesome.rotate.min.css"/>
    
            <meta name="viewport" content="width=device-width,
                initial-scale=1.0, maximum-scale=1.0, user-scalable=no" />
            <style>
                #map_aa8f8673b9154d89a1012cfb12f93a5d {
                    position: relative;
                    width: 100.0%;
                    height: 100.0%;
                    left: 0.0%;
                    top: 0.0%;
                }
            </style>
        
</head>
<body>    
    
            <div class="folium-map" id="map_aa8f8673b9154d89a1012cfb12f93a5d" ></div>
        
</body>
<script>    
    
            var map_aa8f8673b9154d89a1012cfb12f93a5d = L.map(
                "map_aa8f8673b9154d89a1012cfb12f93a5d",
                {
                    center: [40.35891, 49.834549],
                    crs: L.CRS.EPSG3857,
                    zoom: 13,
                    zoomControl: true,
                    preferCanvas: false,
                }
            );

            

        
    
            var tile_layer_11c547bdaf5d69636cebf08d73c2aa8f = L.tileLayer(
                "https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png",
                {"attribution": "Data by \u0026copy; \u003ca href=\"http://openstreetmap.org\"\u003eOpenStreetMap\u003c/a\u003e, under \u003ca href=\"http://www.openstreetmap.org/copyright\"\u003eODbL\u003c/a\u003e.", "detectRetina": false, "maxNativeZoom": 18, "maxZoom": 18, "minZoom": 0, "noWrap": false, "opacity": 1, "subdomains": "abc", "tms": false}
            ).addTo(map_aa8f8673b9154d89a1012cfb12f93a5d);
        
    
            var marker_c529ff07c9ecd6c318e10725c5e7741b = L.marker(
                [40.35891, 49.834549],
                {}
            ).addTo(map_aa8f8673b9154d89a1012cfb12f93a5d);
        
    
            var icon_59eb1665bf71cdb1a75d1112dd18aa39 = L.AwesomeMarkers.icon(
                {"extraClasses": "fa-rotate-0", "icon": "info-sign", "iconColor": "white", "markerColor": "green", "prefix": "glyphicon"}
            );
            marker_c529ff07c9ecd6c318e10725c5e7741b.setIcon(icon_59eb1665bf71cdb1a75d1112dd18aa39);
        
    
        var popup_957e4c233273a7e39980ff23b2e90d5c = L.popup({"maxWidth": "100%"});

        
            var html_4f188ef0b81c2d26db4dd1055f3f1abc = $(`<div id="html_4f188ef0b81c2d26db4dd1055f3f1abc" style="width: 100.0%; height: 100.0%;">Neftchilar Avenue 78</div>`)[0];
            popup_957e4c233273a7e39980ff23b2e90d5c.setContent(html_4f188ef0b81c2d26db4dd1055f3f1abc);
        

        marker_c529ff07c9ecd6c318e10725c5e7741b.bindPopup(popup_957e4c233273a7e39980ff23b2e90d5c)
        ;

        
    
</script>

restaurant/templates/restaurant/contact.html
{% extends 'restaurant/index.html' %}
{% load static %}
{% load i18n %}
{% include 'restaurant/header.html' %}

{% block content %}
<div class="contact">
    <div class="container">
        <h2 class="contact-title">{% trans "Contact" %}</h2>
        <div class="contact__content">
            <div class="contact-text">
                <p>{% trans "Neftchilar Avenue 78, Seaside Boulevard, Baku" %} </p>
                <p>{% trans "Monday" %} - {% trans "Friday" %} 10:00-00:00
                    {% trans "Saturday" %} - {% trans "Sunday" %} 09:00-02:00 </p>
                <p>+994 55 123 45 67
                    +994 55 123 45 67
                </p>
            </div>
            <img src="{% static 'images/img/contact.png' %}" alt="">
        </div>
    </div>
    <div class="contact__bottom">
        <div class="container">
            <div class="bottom">
                <div>
                    {% trans "Neftchilar Avenue 78, Seaside Boulevard, Baku" %} 
                    <a href="{% url 'restaurant:address' %}"><button>{% trans "View in Map" %}</button></a>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock content %}

restaurant/templates/restaurant/gallery.html
{% extends 'restaurant/index.html' %}
{% load static %}
{% load i18n %}
{% block page_styles %}
<link rel="stylesheet" href="{% static 'css/style.css' %}">
{% endblock page_styles %}
   
{% block content %}
<div class="galery">
    <h1 style="text-transform:uppercase;">{% trans "Gallery" %}</h1>
    <div class="resim1">
    {% for gallery in gallery_images %}
        {% if forloop.counter <= 3 %}
            {% if forloop.counter|divisibleby:3%}
            <img style="padding-right:15px;" src={{gallery.image.url}}  alt="">
            {% else %}
            <img style="padding-left:15px;" src={{gallery.image.url}} alt="">
            {% endif %}
        {% endif %}
    {% endfor %}
    </div>
    <div class="resim2">
        {% for gallery in gallery_images %}
            {% if forloop.counter > 3 and forloop.counter <= 6 %}
                {% if forloop.counter|divisibleby:3%}
                <img style="padding-right:15px;" src={{gallery.image.url}}  alt="">
                {% else %}
                <img style="padding-left:15px;" src={{gallery.image.url}} alt="">
                {% endif %}
            {% endif %}
        {% endfor %}
        </div>
</div>
{% endblock content %}

restaurant/templates/restaurant/header.html
{% load static %}
{% load i18n %}
<!DOCTYPE html>
<html lang="en">
<header class="header menu-header">
    <div class="container">
        <div class="header__content">
            <div class="header__logo">
                <a href="index.html"><img src="{% static 'images/img/logo.png' %}" alt="logo"></a>
            </div>
            <ul class="head_menu">
                <li><a href="{% url 'restaurant:home' %}">{% trans "Home" %}</a></li>
                <li><a href="#haqqimizda">{% trans "About us" %}</a></li>
                <li><a href="{% url 'restaurant:menu' 5 %}">{% trans "Menu" %}</a></li>
                <li><a href="{% url 'restaurant:gallery' %}">{% trans "Gallery" %}</a></li>
                <li><a href="{% url 'restaurant:contact' %}">{% trans "Contact" %}</a></li>
            </ul>
        </div>
    </div>
</header>

restaurant/templates/restaurant/index.html
{% load static %}
{% load i18n %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    {% block page_styles %}
    <link rel="stylesheet" type="text/css" href="{% static 'css/index.css' %}">
    {% endblock page_styles %}
    <title>Qarabag</title>
</head>

<body>
    
    {% include 'restaurant/header.html' %}
    {% block content %}
    <div class="intro" id="ana-sehife">
        <div class="container">
            <div class="intro__content">
                <h1 class="intro__title">Lorem ipsum. Dolor sit.</h1>
                <p class="intro__text">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Eget lacus convallis
                    interdum mollis amet commodo lore.</p>
                <p class="intro__text">Lorem ipsum dolor sit amet, consectetur adipiscing elit.</p>
                <div class="intro__cards">
                    <div class="intro__card">
                        <img src="{% static 'images/img/icon_time.svg' %}" alt="icon">
                        <p>{% trans "Monday" %} - {% trans "Friday" %} 10:00-00:00 <br> {% trans "Saturday" %} - {% trans "Sunday" %} 09:00-02:00</p>
                    </div>
                    <div class="intro__card">
                        <img src="{% static 'images/img/icon_location.svg' %}" alt="icon">
                        <p>{% trans "Neftchilar Avenue 78, Seaside Boulevard, Baku" %} </p>
                    </div>
                    <div class="intro__card">
                        <img src="{% static 'images/img/icon_phone.svg' %}" alt="icon">
                        <p>+994 55 123 45 67</p>
                        <p>+994 55 123 45 67</p>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- About -->
    <div class="haqqimizda" id="haqqimizda">
        <div>
            <img src="{% static 'images/img/about.png' %}" alt="">
        </div>
        <h2>{% trans "About us" %}</h2>
        <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Reiciendis doloribus modi
            rerum magni autem fuga sequi quia labore possimus qui facilis et nostrum obcaecati,
            eos consequatur sunt temporibus asperiores. Et vitae, numquam eveniet sapiente distinctio
            sint necessitatibus harum neque commodi culpa accusantium, ducimus velit hic tenetur impedi
            t dolore! Dolorum, quaerat. Dicta neque quidem debitis earum odit harum adipisci eius sed et
            voluptas illum ut omnis beatae amet accusantium atque, corporis quisquam natus illo qui ratione
            architecto. Iste recusandae maxime, amet atque libero provident est aliquam distinctio perspiciatis
            quasi ducimus laborum enim sequi sed adipisci sint fugit suscipit facilis consequatur exercitationem
            id voluptates facere consequuntur. Commodi, a eaque. Placeat obcaecati nostrum inventore quam officiis
            dicta,
            nobis labore? Porro voluptatem eaque cum eum velit saepe, sed aliquid totam molestias ipsum numquam nihil
            laudantium voluptate tempore! Aspernatur, perferendis culpa possimus incidunt minus voluptates dolores
            deleniti. Tempore ex at fuga facilis, quis similique. Iste aut et, doloremque cumque ducimus rem commodi
            hic quaerat ullam rerum facere? Rem veritatis quasi recusandae deleniti quos tempora tempore aut qui?
            Perferendis, magni reiciendis illum inventore quo nihil vitae ea? Quas, dolores harum alias repudiandae non
            id sit vitae quae esse deleniti aspernatur nihil sapiente sunt at mollitia vero ea possimus ex facilis
            eveniet eaque repellat. Animi omnis officia at obcaecati doloremque repellendus nisi ea nemo exercitationem

        </p>
    </div>


    <div class="menu">
        <div class="container">
            <div class="menu__content">
                <h2 class="menu__title">{% trans "Menu" %}</h2>
                <div class="carousel">
                    {% for lam in last_added_menus %}
                    <div class="carousel_card">
                        <img src={{lam.picture.url}} alt="card">
                        <div>
                            <h4>See the menu</h4>
                            <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. </p>
                        </div>
                    </div>
                    {% endfor %}
                </div>
                <a href="{% url 'restaurant:menu' 5 %}"><button class="btn">{% trans "Menu" %}</button></a> 

            </div>
        </div>
    </div>
    {% endblock content %}

    <footer class="footer">
        <div class="container">
            <div class="footer__content">
                <div class="footer__left">
                    <a href="index.html"><img class="footer__logo" src="img/logo.png" alt=""></a>
                    <select name="language" id="lang_select" onchange="document.location.href=this.value" value="az">
                        {% get_current_language as LANGUAGE_CODE %}
                        {% get_available_languages as LANGUAGES %}
                        {% get_language_info_list for LANGUAGES as languages %}
                        <option value="">{% trans "Language" %}</option>
                        {% for lang in languages %}
                            <option value="/{{lang.code}}/{{request.get_full_path|slice:"4:"}}"> {{lang.name_local}} </option>
                        {% endfor %}
                    </select>
                    <div class="footer__socials">
                        <a href=""><img src="{% static 'images/img/icon_wp.svg' %}" alt=""></a>
                        <a href=""><img src="{% static 'images/img/icon_fb.svg' %}" alt=""></a>
                        <a href=""><img src="{% static 'images/img/icon_ins.svg' %}" alt=""></a>
                    </div>
                </div>
                <div class="footer__right">
                    <ul class="footer__list">
                        <h3 class="footer__title">{% trans "Info" %}</h3>
                        <li class="footer__item">
                            <a href="{% url 'restaurant:gallery' %}" class="footer__link">{% trans "Gallery" %}</a>
                        </li>
                        <li class="footer__item">
                            <a href="{% url 'restaurant:contact' %}" class="footer__link">{% trans "Contact" %}</a>
                        </li>
                        <li class="footer__item">
                            <a href="#haqqimizda" class="footer__link">{% trans "About us" %}</a>
                        </li>
                    </ul>
                    <ul class="footer__list">
                        <h3 class="footer__title">{% trans "Address" %}</h3>
                        <p class="footer__text">{% trans "Neftchilar Avenue 78" %}</p>
                        <p class="footer__text">{% trans "Monday" %} - {% trans "Sunday" %} 09:00-02:00</p>
                        <p class="footer__text">+994 55 123 45 67 </p>
                    </ul>
                </div>
                <button class="back-to-top"><img src="{% static 'images/img/icon_toTop.svg' %}" alt=""></button>
                <button class="chatbot"><img src="{% static 'images/img/chat.png' %}" alt=""></button>
            </div>
        </div>
    </footer>

    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
    <script src="{% static 'js/index.js' %}"></script>
    <script src="{% static 'js/backtotop.js' %}"></script>
</body>
</html>

restaurant/templates/restaurant/menu.html
{% extends 'restaurant/index.html' %}
{% load static %}
{% load i18n %}
{% block content %}
<div class="menu">
    <div class="container">
        <div class="menu__content">
            <h2 class="menu__title">{% trans "Menu" %}</h2>
            <nav class="menu__nav">
                <ul class="menu__list">
                    {% for category in categories %}
                    <li class="menu__item">
                        <a href="{% url 'restaurant:menu' category.id %}">{{category.name}}</a>
                    </li>
                    {% endfor %}
                </ul>
            </nav>
        </div>
    </div>

    {% for menu in menus %}
    {% if forloop.counter|divisibleby:2 %}
    <div class="menu__card red-back">
        <div class="container" id="#">
            <h2 class="menu__card-title" >{{menu.menu_name}}</h2>
            <div class="menu__card-content">
                <img src={{menu.picture.url}}  alt="">
                <div class="menu__card-left">
                    <ul class="menu__card-list">
                        {% for meal in menu.menu_meals.all %}
                        <li class="menu__card-item">
                            <p> {{meal.meal_name}} </p>
                            <h3>$ {{meal.price}}</h3>
                        </li>
                        {% endfor %}
                    </ul>
                </div>
            </div>
        </div>
    </div>
    {% else %}
    <div class="menu__card">
        <div class="container" id="#">
            <h2 class="menu__card-title" >{{menu.menu_name}}</h2>
            <div class="menu__card-content">
                <div class="menu__card-left">
                    <ul class="menu__card-list">
                        {% for meal in menu.menu_meals.all %}
                        <li class="menu__card-item">
                            <p> {{meal.meal_name}} </p>
                            <h3>$ {{meal.price}}</h3>
                        </li>
                        {% endfor %}
                    </ul>
                </div>
                <img src={{menu.picture.url}} alt="">
            </div>
        </div>
    </div>
    {% endif %}
    {% endfor %}
</div>
{% endblock content %}